version: '3'

services:
  demo-dev:
    image: demo-dev
    build:
      context: ../
      dockerfile: ./config-dev-docker/Dockerfile
    container_name: demo-dev
    restart: always
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    expose:
      - 8081
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.4"