pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // stage('Compile & Test') {
        //     steps {
        //         sh 'cd mvn test'
        //     }
        // }


        stage('Deploy') {
            steps {
                sh 'cd demo && mvn package -DskipTests'
                sh 'cd demo && cd target/config-dev-docker && sudo docker-compose down'
                sh 'cd demo && cd target/config-dev-docker && sudo docker-compose up --build -d'
                echo "Despliegue a DEV exitoso"

            }
        }
    }
}
